# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用戶名稱')),
                ('password', models.CharField(max_length=40, verbose_name='用戶密碼')),
                ('email', models.EmailField(max_length=254, verbose_name='用戶郵箱')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活狀態')),
            ],
            options={
                'db_table': 's_user_account',
            },
        ),
    ]
