# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='books', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='books',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
    ]
